### ISSUE TITLE
Migrate to Spring Boot 3

### ISSUE THREAD

**Issue by maxnth** [OCR4all/ocr4all-app#10]
see #9

**Comment by vishalsingh2972** [comment]
> see #9

I see here you have already migrated to spring boot 3 , if not could you assign this to me I can help with the upgrades!

**Comment by maxnth** [comment]
done in [feature/upgrade-spring-boot-3](https://github.com/OCR4all/ocr4all-app/tree/feature/upgrade-spring-boot-3)
